spring:
  application:
    name: basquiat-web-flux-issue
  profiles:
    active: local

---
# local
spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/basquiat?currentSchema=basquiat
    username: basquiat
    password: ""
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      max-life-time: 60m

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
    # Pool 관련 로그 확인용
    io.r2dbc.pool: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG